go-app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/phpinfo', function () {
    phpinfo();
});

Route::get('/', function () {
    return view('home', ['page' => 'home']);
})->name('home');

Route::get('/try', function () {
    dd(app()->routes->getRoutes());
});

// Confirm pages
Route::post('/aliasconfirm', 'AliasController@create')->name('aliasconfirm');
Route::post('/emailconfirm', 'PageController@contactSend')->name('emailconfirm');
Route::view('/reportconfirm', 'reportconfirm')->name('reportconfirm');

// Main pages
Route::get('/about', 'PageController@about')->name('about');
Route::get('/browse', 'BrowseController@index')->name('browse');
Route::get('/browsedt', 'BrowseController@index_datatable_cache')->name('browsedt');
Route::get('/browsedtajax', 'BrowseController@index_datatable_ajax')->name('browsedtajax');
Route::get('/browse/s/', 'BrowseController@search')->name('search');
Route::get('/stats', 'StatsController@index')->name('stats');
Route::get('/faq', 'PageController@FAQ')->name('FAQ');
Route::get('/contact', 'PageController@contact')->name('contact');
Route::get('/profile', 'UserController@details')->name('profile');
Route::get('/api', 'PageController@api')->name('api');
Route::get('/api/v1', 'PageController@api')->name('api');
Route::get('/reveal', 'PageController@revealInfo')->name('revealInfo');

// Specific pages
Route::get('/info/{alias}', 'AliasDetails@info')->name('info');
Route::get('/edit/alias/{alias}', 'AliasController@edit')->name('edit/alias');
Route::post('/update/alias', 'AliasController@update')->name('update/alias');
Route::get('/reveal/{alias}', function (App\Alias $alias){
    return view('reveal', [
        'alias' => $alias->alias,
        'url'   => $alias->url->url
    ]);
});
Route::get('/report/{alias}', 'FlagsController@report')->middleware('auth');
Route::get('/token/generate', 'UserController@generateToken');
Route::get('/token/delete', 'UserController@deleteToken');

// Syndication Feed
Route::get('/feed', 'FeedController@index')->name('feed');
Route::permanentRedirect('/rss', '/feed');
Route::permanentRedirect('/atom', '/feed');

// Admin / backoffice
Route::group([
    'prefix' => 'admin',
    'middleware' => ['admin']
], function () {
    Route::get('/', 'AdminController@index')->name('admin');

    Route::get('aliases', 'AdminController@aliases')->name('admin-aliases');
    Route::get('alias/{alias}', 'AdminController@editAlias')->name('admin-edit-alias');
    Route::delete('alias/delete/{alias}', 'AdminController@deleteAlias')->name('admin-delete-alias');
    Route::post('update/owner', 'AdminController@updateOwner')->name('admin-update-owner');

    Route::get('flags', 'AdminController@flags')->name('admin-flags');
    Route::get('people', 'AdminController@people')->name('admin-people');

    Route::get('blacklist', 'AdminController@blacklist')->name('admin-blacklist');
    Route::post('blacklist/append', 'AdminController@appendToBlacklist')->name('admin-blacklist-append');
    Route::delete('blacklist/delete/{keyword}', 'AdminController@deleteFromBlacklist')->name('admin-blacklist-delete');

    Route::get('advanced', 'AdminController@advanced')->name('admin-advanced');
    Route::post('add/administrator', 'AdminController@addAdministrator')->name('admin-add-administrator');
    Route::get('jobs/reliability_test', 'AdminController@runReliabilityTest')->name('admin-reliability-test');
});


// Login routes
Route::get('/login', 'Auth\LoginController@redirectToProvider')->name('login');
Route::get('/login/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('/logout', 'Auth\LoginController@logout');

// Dynamic routes KEEP AT THE END
Route::get('/{alias}', 'RedirectController');

go-app/app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use App\Alias;
use App\BlacklistItem;
use App\Flag;
use App\Traits\Pagination;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Session;

class AdminController extends Controller
{
    use Pagination;

    public function index()
    {
        return view('admin.home', ['page' => 'Admin', 'sub' => 'none']);
    }

    public function aliases()
    {
        $aliases = Alias::with(['url', 'owners', 'flags']);
        $owners = array();
        $flags = array();
        foreach ($aliases->get() as $alias)
        {
            foreach ($alias->owners as $owner)
                $owners[$alias->alias][] = $owner->email;
            foreach ($alias->flags as $flag)
                $this->increment($flags[$alias->alias], $flag->flag_type);

        }
        $aliases = $aliases->paginate();
        return view('admin.aliases', [
            'page' => 'Admin',
            'sub'  => 'Aliases',
            'displayed_pages' => $this->pagination($aliases),
            'aliases' => $aliases,
            'owners' => $owners,
            'flags' => $flags
        ]);
    }

    public function editAlias(Alias $alias)
    {
        $owners = array();
        foreach ($alias->owners as $owner)
            $owners []= $owner->email;

        return view('admin.edit_alias', [
            'page'              => 'Admin',
            'sub'               => 'Aliases',
            'alias'             => $alias->alias,
            'url'               => $alias->url->url,
            'obsolescence_date' => $alias->obsolescence_date,
            'ttl'               => $alias->obsolescence_date ?: 0,
            'hidden'            => $alias->hidden,
            'owners'            => $owners
        ]);
    }

    public function deleteAlias(Alias $alias)
    {
        $success_message = "Alias \"$alias->alias\" successfully deleted from blacklist";
        $alias->delete();
        Session::flash('status', $success_message);
        return $success_message;
    }

    public function updateOwner(Request $request)
    {
        $owner_email = $request->input('new_owner');
        $alias = Alias::where('alias', $request->input('alias'))->first();
        if (is_null($user = User::where('email', $owner_email)->first()))
            return redirect()->back()->withErrors("The user with email \"$owner_email\" does not exist");
        $alias->owners()->attach($user);
        $alias->save();
        return redirect()->back()->with('status', "$user->username has been added to $alias->alias's owners");
    }

    public function flags()
    {
        $_reports = Flag::with('object')
            ->where('flag_type', 'report')->get();
        $reports = array();
        foreach ($_reports as $report)
            if (!empty($report->object))
                $this->increment($reports, $report->object['alias']);

        $_unaccessible = Flag::with('object')
            ->where('flag_type', 'reliability')->get();
        $unaccessible = array();
        foreach ($_unaccessible as $unreliable)
            if (!empty($unreliable->object))
                $unaccessible[$unreliable->object['url']] = $unreliable;

        $_blacklist = Flag::with('object')
            ->where('flag_type', 'blacklist')->get();
        $blacklist = array();
        foreach ($_blacklist as $item)
            if (!empty($item->object))
                if (isset($item->object['url']))
                    $this->increment($blacklist, $item->object['url']);
                elseif (isset($item->object['alias']))
                    $this->increment($blacklist, $item->object['alias']);

        return view('admin.flags', [
            'page'          => 'Admin',
            'sub'           => 'Flags',
            'reports'       => $reports,
            'unaccessible'  => $unaccessible,
            'blacklist'     => $blacklist,
        ]);
    }

    private function increment(&$array, $key)
    {
        if(!isset($array[$key]))
            $array[$key] = 1;
        else
            $array[$key] += 1;
    }

    public function people()
    {
        $people = User::withCount(['aliases'])->paginate();
        return view('admin.people', [
            'page' => 'Admin',
            'sub'  => 'People',
            'displayed_pages' => $this->pagination($people),
            'people' => $people,
        ]);
    }

    public function blacklist()
    {
        $blacklist = BlacklistItem::pluck('keyword')->all();
        return view('admin.blacklist', [
            'page' => 'Admin',
            'sub'  => 'Blacklist',
            'blacklist' => $blacklist
        ]);
    }

    public function appendToBlacklist(Request $request)
    {
        $validated = $request->validate([
            'keyword' => 'required|unique:blacklist_items|max:255'
        ]);
        $word = new BlacklistItem();
        $word->keyword = $validated['keyword'];
        $word->save();
        return redirect()->back()
                         ->with('status', "Keyword \"$word->keyword\" successfully added to blacklist");
    }

    public function deleteFromBlacklist(BlacklistItem $keyword)
    {
        $success_message = "Keyword \"$keyword->keyword\" successfully deleted from blacklist";
        $keyword->delete();
        Session::flash('status', $success_message);
        return $success_message;
    }

    public function advanced()
    {
        $administrators = User::admin()->get();
        return view('admin.advanced', [
            'page' => 'Admin',
            'sub'  => 'Advanced',
            'administrators' => $administrators
        ]);
    }

    public function addAdministrator(Request $request)
    {
        $new_admin_email = $request->input('new_admin');
        $new_admin       = User::where('email', $new_admin_email)->first();
        if (empty($new_admin))
            return redirect()->back()->withErrors(
                "There is no user with the email address \"$new_admin_email\""
            );
        $new_admin->is_admin = true;
        $new_admin->save();
        return redirect()->back()->with('status', "$new_admin->username is now administrator");
    }

    public function runReliabilityTest()
    {
        dispatch(function () {
            $reliability_test = new \App\Console\ReliabilityTest;
            $reliability_test();
        })->onQueue('reliability_test');
        return redirect()->back()->with('status', 'Reliability test started');
    }
}

go-app/resources/views/admin/advanced.blade.php
@extends('admin.layout')

@section('admin-content')
    <h3 class="tlbx-variant-heading">Advanced</h3>
    <br />

    <div class="row">
        <div class="col-xl-12">
            <div class="row">
                <div class="col-xl-3">
                    <h5>Administrators</h5>
                </div>
                <div class="col-xl-9 float-right">
                    <form method="post" action="/admin/add/administrator" class="form-inline float-right">
                        @csrf
                        <input type="text" name="new_admin" class="form-control form-control-lg"
                               placeholder="Email address"/>
                        <input type="submit" class="btn btn-primary" value="Add administrator"/>
                    </form>
                </div>
            </div>

            <ul class="list-group list-group-flush">
                @foreach($administrators as $administrator)
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-9">
                                {{$administrator->email}}
                            </div>
                            <div class="col-3 text-right">
                                <a href="#" class="btn btn-sm btn-danger">Delete</a>
                            </div>
                        </div>
                    </li>
                @endforeach
            </ul>

        </div>
    </div>

    <br />
    <div class="row">
        <div class="col-xl-4">
            <h3>Admin actions</h3>
            <a href="/admin/jobs/reliability_test" class="btn btn-dark btn-lg m-3">Run reliability test</a>
        </div>
    </div>
@endsection

go-app/resources/views/admin/aliases.blade.php
@extends('admin.layout')

@section('admin-content')
    <h3 class="tlbx-variant-heading">Manage aliases</h3>
    <br />
    <table id="aliases" class="table table-boxed dataTable" >
        <thead>
            <tr>
                <th>Alias</th>
                <th>URL</th>
                <th>{{__('Owner(s)')}}</th>
                <th>{{__('Flags')}}</th>
                <th class="no-sort">Actions</th>
            </tr>
        </thead>
        <tbody>
        @foreach($aliases as $alias)
            <tr>
                <td><a href="/{{{$alias->alias}}}">{{{$alias->alias}}}</a></td>
                <td><a href="/{{{$alias->alias}}}">{{{$alias->url->url}}}</a></td>
                <td>
                    @isset($owners[$alias->alias])
                        {{implode(', ', $owners[$alias->alias])}}
                    @endisset
                </td>
                <td>
                    @isset($flags[$alias->alias])
                        @foreach ($flags[$alias->alias] as $flag => $qty)
                            @if ($flag === 'report')
                                <span class="badge badge-pill badge-danger">{{$flag}} ({{$qty}})</span>
                            @elseif ($flag === 'reliability')
                                <span class="badge badge-pill badge-secondary">{{$flag}} ({{$qty}})</span>
                            @elseif ($flag === 'blacklist')
                                <span class="badge badge-pill badge-warning">{{$flag}} ({{$qty}})</span>
                            @endif
                        @endforeach
                    @endisset
                </td>
                <td style="text-align: center">
                    <a href="/admin/alias/{{$alias->alias}}">edit</a>
                    <a href="/admin/alias/delete/{{$alias->alias}}" class="jquery-postback" data-method="delete">
                        delete
                    </a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
<!--
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            @if(!empty($displayed_pages['before']))
                <li class="page-item">
                    <a class="page-link" href="{{$aliases->url(1)}}" aria-label="Go to first page">
                        <svg class="icon" aria-hidden="true"><use xlink:href="#icon-chevron-last-left"></use></svg>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="{{$aliases->previousPageUrl()}}" aria-label="Go to previous page">
                        <svg class="icon" aria-hidden="true"><use xlink:href="#icon-chevron-left"></use></svg>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                @foreach($displayed_pages['before'] as $number => $url)
                    <li class="page-item">
                        <a class="page-link" href="{{$url}}" aria-current="page">
                            {{$number}}
                        </a>
                    </li>
                @endforeach
            @endif
            <li class="page-item active">
                <a class="page-link" href="#" aria-current="page">
                    {{$aliases->currentPage()}}
                    <span class="sr-only">(Current page)</span>
                </a>
            </li>
            @if(!empty($displayed_pages['after']))
                @foreach($displayed_pages['after'] as $number => $url)
                    <li class="page-item">
                        <a class="page-link" href="{{$url}}" aria-current="page">
                            {{$number}}
                        </a>
                    </li>
                @endforeach
                <li class="page-item">
                    <a class="page-link" href="{{$aliases->nextPageUrl()}}" aria-label="Go to next page">
                        <svg class="icon" aria-hidden="true"><use xlink:href="#icon-chevron-right"></use></svg>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="{{$aliases->url($aliases->lastPage())}}" aria-label="Go to last page">
                        <svg class="icon" aria-hidden="true"><use xlink:href="#icon-chevron-last-right"></use></svg>
                    </a>
                </li>
            @endif
        </ul>
    </nav> -->
@endsection

go-app/resources/views/admin/blacklist.blade.php
@extends('admin.layout')

@section('admin-content')
    <h3 class="tlbx-variant-heading">Manage blacklist</h3>
    <br />
    <div class="row">
        <div class="col-xl-8">
            <h5>Words</h5>
            <div class="list-group">
                @foreach($blacklist as $word)
                <div class="list-group-item list-group-item-borderless">
                    <div class="row">
                        <div class="col-md-8">
                            <span>{{$word}}</span>
                        </div>
                        <div class="col-md-3 offset-md-1 text-right">
                            <a href="/admin/blacklist/delete/{{$word}}"
                               data-method="delete"
                               class="jquery-postback btn btn-danger btn-sm">
                                Delete
                            </a>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
        </div>
        <div class="col-xl-4">
            <h5>New word</h5>
            <form method="post" action="/admin/blacklist/append">
                @csrf
                <div class="form-group mb-2">
                    <input class="form-control form-control-md" required="true" type="text" name="keyword" />
                </div>
                <div class="text-right">
                    <input class="btn btn-secondary btn-sm" type="submit" value="Add" />
                </div>
            </form>
        </div>
    </div>
@endsection

go-app/resources/views/admin/edit_alias.blade.php
@extends('admin.layout')

@section('admin-content')
<a href="/admin/aliases" class="btn btn-primary m-2">
    <svg class="icon" aria-hidden="true" style="vertical-align: initial;">
        <use xlink:href="#icon-arrow-left"></use>
    </svg>
    Back
</a>
<div class="row">
    <div class="col-md-6">
        @include('partials.edit_alias', [
            'prev_url'          => $url,
            'prev_alias'        => $alias,
            'hidden'            => $hidden,
            'obsolescence_date' => $obsolescence_date,
            'action'            => "/admin/update/alias",
            'submitButton'      => 'Update'
        ])
    </div>
    <div class="col-md-6">
        <h3>Owners</h3>
        <ul>
            @foreach($owners as $owner)
                <li>{{$owner}}</li>
            @endforeach
        </ul>
        <div class="row">
            <div class="col-md-12">
                <form method="post" action="/admin/update/owner" class="form-inline">
                    @csrf
                    <input type="hidden" name="alias" value="{{{$alias}}}" />
                    <input style="width: 80%;" type="text" name="new_owner" class="form-control form-control-lg" />
                    <input type="submit" class="btn btn-primary" value="Add owner"/>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

go-app/resources/views/admin/flags.blade.php
@extends('admin.layout')

@section('admin-content')
    <h3 class="tlbx-variant-heading">Manage flags 🚩</h3>
    <br />
    <div class="row">
        <div class="col-xl-4">
            <h5>Reports</h5>
            <table class="table dataTableSimple">
                <thead>
                    <tr>
                        <th>Alias</th>
                        <th>Reports count</th>
                        <th class="no-sort">Details</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($reports as $alias => $reports_count)
                    <tr>
                        <td>{{$alias}}</td>
                        <td>{{$reports_count}} 🚩</td>
                        <td><a href="/reports/{{$alias}}">details</a></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="col-xl-4">
            <h5>Unreliable</h5>
            <table class="table">
                <tbody>
                @foreach($unaccessible as $url => $unreliable)
                    <tr>
                        <td>{{$url}}</td>
                        <td>{{$unreliable->details['status_code']}}</td>
                        <td><a href="/unreliable/{{$unreliable->id}}">details</a></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="col-xl-4">
            <h5>Blacklist</h5>
            <table class="table">
                <tbody>
                @foreach($blacklist as $object => $blacklist_count)
                    <tr>
                        <td>
                            {{$object}} ({{$blacklist_count}})
                        </td>
                        <td><a href="/blacklist/{{$blacklisted->id}}">details</a></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

go-app/resources/views/admin/home.blade.php
@extends('admin.layout')
@section('admin-content')
    <h3 class="tlbx-variant-heading">Backoffice</h3>
    @auth
    <br />
    [WIP]
    <h5>Actions</h5>
    <p>This is a list of idea of kind of action administrators might have to do:
    <ul>
        <li><a href="#">💡 See reported URL</a></li>
        <li><a href="#">💡 See URLs that return 404</a></li>
        <li><a href="#">💡 Resolve claimed URL</a></li>
        <li><a href="#">💡 See URLs submitted by a user</a></li>
        <li><a href="#">💡 Transfer authority of user's URLs to another one</a></li>
        <li><a href="#">💡 ...</a></li>
    </ul>
    @endauth
    @guest
    <span>Only admins are allowed here. Please <a href="/login">login</a> if you are granted here.</span>
    @endguest
@endsection

go-app/resources/views/admin/layout.blade.php
@extends('layouts.skeleton')
@section('body')
    <div class="container-fluid">
        @include('layouts.errors')
        <div class="row">
            <div class="col-md-3">
                <nav
                    id="nav-aside"
                    class="nav-aside"
                    role="navigation"
                    aria-describedby="nav-aside-title"
                >
                    <h2 class="h5 sr-only-xl">{{__('Submenu')}}</h2>
                    <ul>
                        <li class="{{$sub === 'Aliases' ? 'active' : ''}}">
                            <a href="/admin/aliases">{{__('Aliases')}}</a></li>
                        <li class="{{$sub === 'Flags' ? 'active' : ''}}">
                            <a href="/admin/flags">{{__('Flags')}}</a></li>
                        <li class="{{$sub === 'People' ? 'active' : ''}}">
                            <a href="/admin/people">{{__('People')}}</a></li>
                        <li class="{{$sub === 'Blacklist' ? 'active' : ''}}">
                            <a href="/admin/blacklist">{{__('Blacklist')}}</a></li>
                        <li class="{{$sub === 'Advanced' ? 'active' : ''}}">
                            <a href="/admin/advanced">{{__('Advanced')}}</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-md-9">
                @yield('admin-content')
            </div>
        </div>
    </div>
@endsection

@section('javascript')
<script>
    $(function() {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $(document).on('click', 'a.jquery-postback', function (e) {
            e.preventDefault(); // does not go through with the link.

            var $this = $(this);

            $.post({
                type: $this.data('method'),
                url: $this.attr('href')
            }).done(function (data) {
                console.log(data);
                location.reload();
            });
        });
    })
</script>
@endsection

go-app/resources/views/admin/people.blade.php
@extends('admin.layout')

@section('admin-content')
    <h3 class="tlbx-variant-heading">Manage users</h3>
    <br />
    <table id="people" class="table dataTable table-boxed" >
        <thead>
            <tr>
                <th>Email</th>
                <th>Aliases count</th>
                <th class="no-sort">API Token</th>
            </tr>
        </thead>
        <tbody>
        @foreach($people as $user)
            <tr>
                <td>{{$user->email}}</td>
                <td>{{$user->aliases_count}}</td>
                <td style="text-align: center">
                    @isset($user->api_token)
                        <a href="#">revoke</a>
                        <a href="#">regenerate</a>
                    @else
                        <a href="#">generate</a>
                    @endisset
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
<!--
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            @if(!empty($displayed_pages['before']))
                <li class="page-item">
                    <a class="page-link" href="{{$people->url(1)}}" aria-label="Go to first page">
                        <svg class="icon" aria-hidden="true"><use xlink:href="#icon-chevron-last-left"></use></svg>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="{{$people->previousPageUrl()}}" aria-label="Go to previous page">
                        <svg class="icon" aria-hidden="true"><use xlink:href="#icon-chevron-left"></use></svg>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                @foreach($displayed_pages['before'] as $number => $url)
                    <li class="page-item">
                        <a class="page-link" href="{{$url}}" aria-current="page">
                            {{$number}}
                        </a>
                    </li>
                @endforeach
            @endif
            <li class="page-item active">
                <a class="page-link" href="#" aria-current="page">
                    {{$people->currentPage()}}
                    <span class="sr-only">(Current page)</span>
                </a>
            </li>
            @if(!empty($displayed_pages['after']))
                @foreach($displayed_pages['after'] as $number => $url)
                    <li class="page-item">
                        <a class="page-link" href="{{$url}}" aria-current="page">
                            {{$number}}
                        </a>
                    </li>
                @endforeach
                <li class="page-item">
                    <a class="page-link" href="{{$people->nextPageUrl()}}" aria-label="Go to next page">
                        <svg class="icon" aria-hidden="true"><use xlink:href="#icon-chevron-right"></use></svg>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="{{$people->url($aliases->lastPage())}}" aria-label="Go to last page">
                        <svg class="icon" aria-hidden="true"><use xlink:href="#icon-chevron-last-right"></use></svg>
                    </a>
                </li>
            @endif
        </ul>
    </nav> -->
@endsection