go-app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/phpinfo', function () {
    phpinfo();
});

Route::get('/', function () {
    return view('home', ['page' => 'home']);
})->name('home');

Route::get('/try', function () {
    dd(app()->routes->getRoutes());
});

// Confirm pages
Route::post('/aliasconfirm', 'AliasController@create')->name('aliasconfirm');
Route::post('/emailconfirm', 'PageController@contactSend')->name('emailconfirm');
Route::view('/reportconfirm', 'reportconfirm')->name('reportconfirm');

// Main pages
Route::get('/about', 'PageController@about')->name('about');
Route::get('/browse', 'BrowseController@index')->name('browse');
Route::get('/browsedt', 'BrowseController@index_datatable_cache')->name('browsedt');
Route::get('/browsedtajax', 'BrowseController@index_datatable_ajax')->name('browsedtajax');
Route::get('/browse/s/', 'BrowseController@search')->name('search');
Route::get('/stats', 'StatsController@index')->name('stats');
Route::get('/faq', 'PageController@FAQ')->name('FAQ');
Route::get('/contact', 'PageController@contact')->name('contact');
Route::get('/profile', 'UserController@details')->name('profile');
Route::get('/api', 'PageController@api')->name('api');
Route::get('/api/v1', 'PageController@api')->name('api');
Route::get('/reveal', 'PageController@revealInfo')->name('revealInfo');

// Specific pages
Route::get('/info/{alias}', 'AliasDetails@info')->name('info');
Route::get('/edit/alias/{alias}', 'AliasController@edit')->name('edit/alias');
Route::post('/update/alias', 'AliasController@update')->name('update/alias');
Route::get('/reveal/{alias}', function (App\Alias $alias){
    return view('reveal', [
        'alias' => $alias->alias,
        'url'   => $alias->url->url
    ]);
});
Route::get('/report/{alias}', 'FlagsController@report')->middleware('auth');
Route::get('/token/generate', 'UserController@generateToken');
Route::get('/token/delete', 'UserController@deleteToken');

// Syndication Feed
Route::get('/feed', 'FeedController@index')->name('feed');
Route::permanentRedirect('/rss', '/feed');
Route::permanentRedirect('/atom', '/feed');

// Admin / backoffice
Route::group([
    'prefix' => 'admin',
    'middleware' => ['admin']
], function () {
    Route::get('/', 'AdminController@index')->name('admin');

    Route::get('aliases', 'AdminController@aliases')->name('admin-aliases');
    Route::get('alias/{alias}', 'AdminController@editAlias')->name('admin-edit-alias');
    Route::delete('alias/delete/{alias}', 'AdminController@deleteAlias')->name('admin-delete-alias');
    Route::post('update/owner', 'AdminController@updateOwner')->name('admin-update-owner');

    Route::get('flags', 'AdminController@flags')->name('admin-flags');
    Route::get('people', 'AdminController@people')->name('admin-people');

    Route::get('blacklist', 'AdminController@blacklist')->name('admin-blacklist');
    Route::post('blacklist/append', 'AdminController@appendToBlacklist')->name('admin-blacklist-append');
    Route::delete('blacklist/delete/{keyword}', 'AdminController@deleteFromBlacklist')->name('admin-blacklist-delete');

    Route::get('advanced', 'AdminController@advanced')->name('admin-advanced');
    Route::post('add/administrator', 'AdminController@addAdministrator')->name('admin-add-administrator');
    Route::get('jobs/reliability_test', 'AdminController@runReliabilityTest')->name('admin-reliability-test');
});


// Login routes
Route::get('/login', 'Auth\LoginController@redirectToProvider')->name('login');
Route::get('/login/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('/logout', 'Auth\LoginController@logout');

// Dynamic routes KEEP AT THE END
Route::get('/{alias}', 'RedirectController');

go-app/app/Http/Controllers/FeedController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Response;
use Illuminate\Support\Facades\Log;
use App\Alias;

/**
 * This class create a Atom Syndication
 * See https://tools.ietf.org/html/rfc4287
 * See https://validator.w3.org/feed/docs/atom.html
 */
class FeedController extends Controller
{
    public $feed;

    public function index()
    {
        // Define the feed metadata
        $this->getFeedMetadata();
        $this->getFeedEntries();
        // Get the view's content
        $content = view('layouts.feed', ['feed' => $this->feed]);
        // Return the HTTP response with the content specifying the header's 
        // Content-Type to text/xml 
        // (see https://stackoverflow.com/a/3272572/960623)
        return response($content, 200)
                ->header('Content-Type', 'text/xml');
    }
    
    /**
     * Set the metadata elements of the feed
     **/
    private function getFeedMetadata()
    {
        $this->feed                = (object)[];
        $this->feed->title         = 'Go.epfl.ch\'s syndication feed';
        $this->feed->link          = 'https://go.epfl.ch/feed';
        $this->feed->updated       = date('c');
        $this->feed->author        = (object)[];
        $this->feed->author->name  = 'Go.epfl.ch\'s admins';
        $this->feed->author->email = 'go@groupes.epfl.ch';
        $this->feed->author->uri   = 'https://go.epfl.ch/contact';
        $this->feed->id            = 'urn:uuid:7d90b9a3-b584-4aae-ae76-db1b5823cf82';
    }
    
    /**
     * Set the entries elements of the feed
     **/
    private function getFeedEntries()
    {
        $this->feed->entries = Alias::public()
                                ->withCount('clicks')
                                ->leftJoin('urls', 'aliases.url_id', '=', 'urls.id')
                                ->orderby('aliases.created_at', 'DESC')
                                ->limit(30)
                                ->get();
    }
}

go-app/resources/views/layouts/app.blade.php
@extends('layouts.skeleton')
@section('body')
    <div class="main-container">
        @include('layouts.menu.mobile.menu')
        <div id="app-layout" class="container">
            <main class="py-4">
                @include('layouts.errors')
                @yield('content')
            </main>
        </div>
    </div>
@endsection

go-app/resources/views/layouts/empty.blade.php
@if ($errors->any())
    @foreach ($errors->all() as $error)
        {{{$error}}}
    @endforeach
@endif
@yield('content')

go-app/resources/views/layouts/errors.blade.php
@if ($errors->any())
  <div id="errors">
    @foreach ($errors->all() as $error)
      <div class="error_message alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Watch out !</strong> {{{$error}}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    @endforeach
  </div>
@endif

@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif

go-app/resources/views/layouts/feed.blade.php
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">

  <title>{{ $feed->title }}</title>
  <link href="{{ $feed->link }}"/>
  <updated>{{ $feed->updated }}</updated>
  <author>
    <name type="html">{{ $feed->author->name }}</name>
    <email>{{ $feed->author->email }}</email>
    <uri>{{ $feed->author->uri }}</uri>
  </author>
  <id>{{ $feed->id }}</id>

  @foreach ($feed->entries as $entry)
    @include('layouts.feedEntry')
  @endforeach
</feed>

go-app/resources/views/layouts/feedEntry.blade.php
  <entry>
    <title type="html">{{ env('APP_URL') }}{{ $entry->alias }} → {{{$entry->url->url}}}</title>
    <link href="{{ env('APP_URL') }}{{ $entry->alias }}"/>
    <id>tag:{{ env('APP_URL') }}{{ $entry->alias }}:@php echo sha1($entry->alias); @endphp</id>
    <updated>{{ $entry->updated_at }}</updated>
    <created>{{ $entry->created_at }}</created>
    <summary type="html">
      <![CDATA[
      The link <a href="{{ env('APP_URL') }}{{ $entry->alias }}">{{{$entry->url->url}}}</a> 
      has been shortened on {{ $entry->created_at }}.
      <br />
      Its alias is <b>{{ $entry->alias }}</b>.
      <br />
      It has been clicked {{ $entry->clicks_count }} times.
      <br />
      Please visit it here: <a href="{{ env('APP_URL') }}{{ $entry->alias }}">{{{$entry->url->url}}}</a>.
      <br /><hr />
      <a href="{{ env('APP_URL') }}">go.epfl.ch</a> — EPFL URL shortener (<a href="{{ env('APP_URL') }}/contact">contact</a>)
      ]]>
    </summary>
  </entry>

go-app/resources/views/layouts/footer.blade.php
<?php # https://epfl-idevelop.github.io/elements/#/organisms/footer/light-dark-en/full ?>
<footer class="footer-light fixed-bottom d-none d-md-block" role="contentinfo">
  <div class="tlbx-component-footer-light-dark-en bg-dark">
    <div>&nbsp;
      <!-- poor man's space on Friday's night -->
    </div>
    <div class="row">
      <div class="col-xl-11 mx-xl-auto">
        <div class="row">
          <div class="col-6 mx-auto mx-md-0 mb-4 col-md-3 col-lg-2">
            <a href="#">
              <img src="/svg/epfl-logo-negative.svg" alt="Logo EPFL, École polytechnique fédérale de Lausanne" class="img-fluid">
            </a>
          </div>
          <div class="col-md-9 col-lg-10">
            <div class="ml-md-2 ml-lg-5">
              <ul class="list-inline list-unstyled">
                <li class="list-inline-item text-white">Contact</li>
                <li class="list-inline-item text-gray-300 pl-3"><small>EPFL CH-1015 Lausanne</small></li>
                <li class="list-inline-item text-gray-300 pl-3"><small>+41 21 693 11 11</small></li>
              </ul>
              <p class="footer-light-socials">
                <small>Follow the EPFL on social media</small>
                <span>
                  <a href="https://www.facebook.com/epflcampus" class="social-icon social-icon-facebook social-icon-negative">
                    <svg class="icon" aria-hidden="true">
                      <use xlink:href="#icon-facebook"></use>
                    </svg>
                    <span class="sr-only">Follow us on Facebook.</span>
                  </a>
                  <a href="https://twitter.com/epfl" class="social-icon social-icon-twitter social-icon-negative">
                    <svg class="icon" aria-hidden="true">
                      <use xlink:href="#icon-twitter"></use>
                    </svg>
                    <span class="sr-only">Follow us on Twitter.</span>
                  </a>
                  <a href="http://instagram.com/epflcampus" class="social-icon social-icon-instagram social-icon-negative">
                    <svg class="icon" aria-hidden="true">
                      <use xlink:href="#icon-instagram"></use>
                    </svg>
                    <span class="sr-only">Follow us on Instagram.</span>
                  </a>
                  <a href="https://www.youtube.com/user/epflnews" class="social-icon social-icon-youtube social-icon-negative">
                    <svg class="icon" aria-hidden="true">
                      <use xlink:href="#icon-youtube"></use>
                    </svg>
                    <span class="sr-only">Follow us on Youtube.</span>
                  </a>
                  <a href="https://www.linkedin.com/school/epfl/" class="social-icon social-icon-linkedin social-icon-negative">
                    <svg class="icon" aria-hidden="true">
                      <use xlink:href="#icon-linkedin"></use>
                    </svg>
                    <span class="sr-only">Follow us on LinkedIn.</span>
                  </a>
                </span>
              </p>

              <div class="footer-legal">
                <div class="footer-legal-links">
                  <a href="https://epfl-idevelop.github.io/elements/#/doc/accessibility.html">{{ __('Accessibility') }}</a>
                  <a href="https://www.epfl.ch/about/overview/overview/regulations-and-guidelines/">{{ __('Legals') }}</a>
                  <a href="{{ route('contact') }}">{{ __('Contact') }}</a>
                  <a href="https://gitlab.com/epfl-idevfsd/go-epfl">{{ __('Source code') }}</a>&nbsp;<p id="app_version">{{$app_version}}</p>
                </div>
                <div>
                  <p>&copy; 2018-<?php echo date('Y') ?> {{ __('EPFL, all rights reserved') }}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

go-app/resources/views/layouts/header.blade.php
{{-- From EPFL https://epfl-idevelop.github.io/elements/#/organisms/header/light-fr/full --}}
<header role="banner" class="header header-light navbar-laravel" id="app-layout">
  <div class="drawer mr-3 mr-xl-0">
    <button class="drawer-toggle">
      <svg class="icon" aria-hidden="true"><use xlink:href="#icon-chevron-right"></use></svg>
    </button>
    <a href="//www.epfl.ch" class="drawer-link">
      <span class="text">
        Go to EPFL main site
      </span>
    </a>
  </div>

  <div class="header-light-content">
    <a class="logo" href="/">
      <img src="/svg/epfl-logo.svg" alt="Logo EPFL, École polytechnique fédérale de Lausanne" class="img-fluid">
    </a>
    <h1><acronyme title="EPFL URL Shortener">go.epfl.ch</acronyme></h1>

    @include('layouts.menu.menu')

    @include('layouts.menu.mobile.search')
    @include('layouts.menu.partials.search')

    <nav class="nav-lang nav-lang-short ml-auto">
      <!-- Right Side Of Navbar -->
      <ul class="navbar-nav ml-auto">
        <!-- Authentication Links -->
        @guest
          <li class="nav-item">
            <span><a href="{{ route('login') }}">{{ __('Login') }}</a></span>
          </li>
        @else
          <li class="nav-item">
            <span><a href="/admin/">{{ __('Admin') }}</a></span>
          </li>
          <li class="nav-item">
            <span><a href="/profile">{{ Auth::user()->username }} ⌅</a></span>
          </li>
          <li class="nav-item">
            <span><a href="/logout">{{ __('Logout') }} →</a></span>
          </li>
        @endguest
      </ul>
      <ul>
        <li>
          <a href="#" aria-label="Français" alt="">FR</a>
        </li>
        <li>
          <span class="active" aria-label="English">EN</span>
        </li>
      </ul>
    </nav>

    @include('layouts.menu.mobile.burger')

  </div>

</header>

go-app/resources/views/layouts/httperrors.blade.php
@extends('layouts.app')

@section('content')
  <div class="row">
    <div class="col-8">
      <h2>@yield('title')</h2>
    </div>
    <div class="col-4">
      <h2>@yield('code')</h2>
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-12">
      <p>
        @yield('message')
      </p>
      <p>
        The server returned the HTTP status code <b>@yield('code')</b> "@yield('title')".
        <br />
        You can have more information about this status code <a href="https://httpstatuses.com/@yield('code')" target="_blank">here</a>...
      </p>
      <p>
        If you think that should not have happened, please contact us <a href="/contact">here</a>. Otherwise, head back to the <a href="/">homepage</a>.
      </p>
    </div>
  </div>
@endsection

go-app/resources/views/layouts/skeleton.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'go.epfl.ch') }}</title>
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="alternate" type="application/atom+xml" title="Go.epfl.ch's syndication feed" href="/feed">

    @include('layouts.partials.cookieconsent')

</head>

<body data-spy="scroll" data-target="#intermediate-nav" data-offset="0">

@include('layouts.header')
@yield('body')
@include('layouts.footer')
<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
@yield('javascript')
</body>

</html>